# Generated by Django 6.0.1 on 2026-01-20 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user_update', models.JSONField(blank=True, default=dict, help_text='What the user said during this check-in')),
                ('summary', models.TextField(help_text='Aura’s concise summary of the check-in')),
                ('advice', models.TextField(help_text='Guidance Aura gave the user')),
                ('focus_until_next', models.CharField(help_text='Single primary financial focus', max_length=255)),
                ('confidence_score', models.PositiveSmallIntegerField(default=80, help_text='0–100 confidence in data accuracy')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('primary_goal', models.CharField(max_length=255)),
                ('financial_context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='finance.financialprofile')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
